# Generated by Django 4.2.1 on 2023-05-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField()),
                ('userfile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
